export const black = [
  {
    src: "audio/black/Acalanto.mp3",
    name: "Acalanto",
    band: "Black do Acordeon e Barbara Greco",
    type: "lenta",
  },
  {
    src: "audio/black/Baiao.mp3",
    name: "Baião",
    band: "Dominguinhos, Sivuca, Oswaldinho",
    type: "rapida",
  },
  {
    src: "audio/black/Alumiou.mp3",
    name: "Alumiou",
    band: "Ó do forrò",
    type: "lenta",
  },
  {
    src: "audio/black/Cascaxado.mp3",
    name: "Cascaxado",
    band: "Cascabulho",
    type: "rapida",
  },
  {
    src: "audio/black/Carinho-do-Bom.mp3",
    name: "Carinho do Bom",
    band: "Jaime",
    type: "lenta",
  },
  {
    src: "audio/black/Forro-de-Printemps.mp3",
    name: "Forro-de-Printemps.",
    band: "Forró Pifado",
    type: "rapida",
  },
  {
    src: "audio/black/Caxixi.mp3",
    name: "Caxixi",
    band: "Mariene de Castro",
    type: "lenta",
  },
  {
    src: "audio/black/Lamento-Sertanejo.mp3",
    name: "Lamento-Sertanejo",
    band: "Nicolas Krassik, Daniela Spielman",
    type: "rapida",
  },
  {
    src: "audio/black/EITA.mp3",
    name: "EITA",
    band: "Giseli de Santi",
    type: "lenta",
  },
  {
    src: "audio/black/Pe-De-Calcada.mp3",
    name: "Pe-De-Calcada",
    band: "Mestre Ambrósio",
    type: "rapida",
  },
  {
    src: "audio/black/Naise.mp3",
    name: "Naise",
    band: "Nina Oliveira",
    type: "lenta",
  },
  {
    src: "audio/black/Retrato-de-um-Forro.mp3",
    name: "Retrato-de-um-Forro",
    band: "Paulinho do Acordeon",
    type: "rapida",
  },
  {
    src: "audio/black/Onde-Esta-Voce.mp3",
    name: "Onde Está Você",
    band: "Mariana Aydar",
    type: "lenta",
  },
  {
    src: "audio/black/Feira de Mangaio.mp3",
    name: "Feira de Mangaio Instrumental",
    band: "Dominguinos",
    type: "rapida",
  },
  {
    src: "audio/black/Platonismo.mp3",
    name: "Platonismo",
    band: "Bicho de Pé, Janayna Pereira",
    type: "lenta",
  },
  {
    src: "audio/black/Sebastiana.mp3",
    name: "Sebastiana",
    band: "Rastapé",
    type: "rapida",
  },
  {
    src: "audio/black/Riso-Frouxo.mp3",
    name: "Riso Frouxo",
    band: "Bárbara Greco",
    type: "lenta",
  },
  {
    src: "audio/black/Esquisitice.mp3",
    name: "Esquisitice",
    band: "As Bastianas",
    type: "rapida",
  },
  {
    src: "audio/black/Tom-de-Alegria.mp3",
    name: "Tom de Alegria",
    band: "Zaíra",
    type: "lenta",
  },
  {
    src: "audio/black/Arpoador (2).mp3",
    name: "Arpoador",
    band: "Os Cincopados",
    type: "rapida",
  },
  {
    src: "audio/black/Aldeia.mp3",
    name: "Aldeia",
    band: "Estakazero",
    type: "rapida",
  },
  {
    src: "audio/black/Balada do Pó, Pedra e Caminho.mp3",
    name: "Balada do Pó, Pedra e Caminho",
    band: "Forró Massapê",
  },
  {
    src: "audio/black/Hino Malino.mp3",
    name: "Hino Malino",
    band: "Forró Malino",
    type: "rapida",
  },
  {
    src: "audio/black/Celebrai.mp3",
    name: "Celebrai",
    band: "Relô Rolô",
    type: "lenta",
  },
  {
    src: "audio/black/Ao meu lado é seu lugar.mp3",
    name: "Ao meu lado é seu lugar",
    band: "Circuladô de Fulô",
    type: "rapida",
  },
  {
    src: "audio/black/Porque Tem Que Ser Assim.mp3",
    name: "Porque Tem Que Ser Assim",
    band: "Cezzinha",
    type: "lenta",
  },
  {
    src: "audio/black/Bicho Do Mato.mp3",
    name: "Bicho Do Mato",
    band: "Rastapé",
    type: "rapida",
  },
  {
    src: "audio/black/Espere por mim morena.mp3",
    name: "Espere por mim morena",
    band: "Caraivana",
    type: "lenta",
  },
  {
    src: "audio/black/Cinco pra Xaxar.mp3",
    name: "Cinco pra Xaxar",
    band: "Forró",
    type: "rapida",
  },
  {
    src: "audio/black/Lisbela.mp3",
    name: "Lisbela",
    band: "Los Hermanos",
    type: "lenta",
  },
  {
    src: "audio/black/De Frente Pro Mar.mp3",
    name: "De Frente Pro Mar",
    band: "Estakazero",
    type: "rapida",
  },
  {
    src: "audio/black/Surpresa Boa.mp3",
    name: "Surpresa Boa",
    band: "Luso Baião",
    type: "lenta",
  },
  {
    src: "audio/black/Noite Severina.mp3",
    name: "Noite Severina",
    band: "Lila Queiroga",
    type: "lenta",
  },
  {
    src: "audio/black/Nós Dois.mp3",
    name: "Nós Dois",
    band: "Forro Raíz",
    type: "lenta",
  },
  {
    src: "audio/black/Filosofia.mp3",
    name: "Filosofia",
    band: "Flávio José",
    type: "rapida",
  },
  {
    src: "audio/black/Ócio Criativo.mp3",
    name: "Ócio Criativo",
    band: "Manitu",
    type: "lenta",
  },
  {
    src: "audio/black/Nem Mesmo Eu.mp3",
    name: "Nem Mesmo Eu",
    band: "Boi de Lata",
    type: "rapida",
  },
  {
    src: "audio/black/Por causa de você menina.mp3",
    name: "Por causa de você menina",
    band: "Buchicho",
    type: "lenta",
  },
  {
    src: "audio/black/Pout-Pourri.mp3",
    name: "Pot-Pourri",
    band: "Fkávio José",
    type: "rapida",
  },
  {
    src: "audio/black/Saber Voar.mp3",
    name: "Saber Voar",
    band: "Chimarruts",
    type: "lenta",
  },
  {
    src: "audio/black/Voz do coração.mp3",
    name: "Voz do coração",
    band: "Ó do Forró",
    type: "lenta",
  },
];
