export const blueadv = [
    {
        src: 'audio/blueadv/Miou.mp3',
        name: 'Miou',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Morena não se vá.mp3',
        name: 'Morena não se vá',
        band: 'Chama Chuva',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/A Notícia.mp3',
        name: 'A Notícia',
        band: 'Vicente Barreto',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Não Há Nada Igual ao Forró.mp3',
        name: 'Não Há Nada Igual ao Forró',
        band: 'Bicho de Pé',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Carta de um Anjo.mp3',
        name: 'Carta de um Anjo',
        band: 'Falamansa',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Acerola.mp3',
        name: 'Acerola',
        band: 'Verso e Prosa',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Mãe liberdade.mp3',
        name: 'Mãe Liberdade',
        band: 'Relô Rolô',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Baile da Tartaruga.mp3',
        name: 'Baile da Tartaruga',
        band: 'Zé Gonzaga',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Minha distância.mp3',
        name: 'Minha Distância',
        band: 'Trio Alvorada',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Canção dos Amigos.mp3',
        name: 'Canção dos Amigos',
        band: 'Kanavia',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/nossos olhos-1.mp3',
        name: 'Nossos Olhos',
        band: 'Forró Massapê',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/É Proibido Cochilar.mp3',
        name: 'É Proibido Cochilar',
        band: 'Circuladô de Fulô',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Outra Vida.mp3',
        name: 'Outra Vida',
        band: 'Armandinho',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Em contato corpo e alma.mp3',
        name: 'Em Contato Corpo e Alma',
        band: 'Trio Juremá',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Pescador (Só Parênt).mp3',
        name: 'Pescador',
        band: 'Só Parênt',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Exame.mp3',
        name: 'Exame Instrumental',
        band: 'Instrumental',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Quem me dera.mp3',
        name: 'Quem Me Dera',
        band: 'Circuladô de Fulô',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Magamalabares.mp3',
        name: 'Magamalabares',
        band: 'Circuladô de Fulô',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Recado.mp3',
        name: 'Recado',
        band: 'Cezinha',
        type: 'lenta',
    },
    {
        src: 'audio/blueadv/Mensageiro de um Rei.mp3',
        name: 'Mensageiro de um Rei',
        band: 'Fenfit',
        type: 'rapida',
    },
    {
        src: './src/black/fastBlack/Aldeia.mp3',
        name: 'Aldeia',
        band: 'Estakazero',
        type: 'rapida',
    },
    {
        src: 'audio/blueadv/Toc Toc.mp3',
        name: 'Toc Toc',
        band: 'Verso e Prosa',
    },
]