export const blueadv = [
  {
    src: "audio/blueadv/No colo do teu coraçcao.mp3",
    name: "No colo do teu coraçcao",
    band: "Falamansa",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Cabeca DAgua.mp3",
    name: "Cabeca DAgua",
    band: "Chama Chuva",
    type: "rapida",
  },
  {
    src: "audio/blueadv/De tardezinha.mp3",
    name: "De tardezinha",
    band: "Vicente Barreto",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Não Há Nada Igual ao Forró.mp3",
    name: "Não Há Nada Igual ao Forró",
    band: "Bicho de Pé",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Segue a Vida.mp3",
    name: "Segue a Vida",
    band: "Falamansa",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Roseira do Norte.mp3",
    name: "Roseira do Norte",
    band: "Verso e Prosa",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Dois Pra Ca.mp3",
    name: "Dois Pra Ca",
    band: "Relô Rolô",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Embalo Do Forro.mp3",
    name: "Embalo Do Forro",
    band: "Zé Gonzaga",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Essa musica.mp3",
    name: "Essa musica",
    band: "Trio Alvorada",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Canção dos Amigos.mp3",
    name: "Canção dos Amigos",
    band: "Kanavia",
    type: "rapida",
  },
  {
    src: "audio/blueadv/I Love You So.mp3",
    name: "I Love You So",
    band: "Verso e Prosa",
    type: "lenta",
  },
  {
    src: "audio/blueadv/É Proibido Cochilar.mp3",
    name: "É Proibido Cochilar",
    band: "Circuladô de Fulô",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Pra Que Fingir.mp3",
    name: "Pra Que Fingir",
    band: "Armandinho",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Instrumental 1D2.mp3",
    name: "Instrumental 1D2",
    band: "Trio Juremá",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Benzin.mp3",
    name: "Benzin",
    band: "Só Parênt",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Abc do Sertão.mp3",
    name: "Abc do Sertão Instrumental",
    band: "Instrumental",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Erro eu.mp3",
    name: "Erro eu",
    band: "Circuladô de Fulô",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Magamalabares.mp3",
    name: "Magamalabares",
    band: "Circuladô de Fulô",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Despedida.mp3",
    name: "Despedida",
    band: "Cezinha",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Forro Em Arcoverde - Vai E Vem.mp3",
    name: "Forro Em Arcoverde - Vai E Vem",
    band: "Fenfit",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Cheira Bem.mp3",
    name: "Cheira Bem",
    band: "Cezinha",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Rosalina.mp3",
    name: "Rosalina",
    band: "Estakazero",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Chegue devagar - Filpo e a Feira.mp3",
    name: "Chegue devagar - Filpo e a Feira",
    band: "Cezinha",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Forro Universitario.mp3",
    name: "Forro Universitario",
    band: "Verso e Prosa",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Pra Segurar Meu Coração.mp3",
    name: "Pra Segurar Meu Coração",
    band: "Cezinha",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Forro No Claro.mp3",
    name: "Forro No Claro",
    band: "Verso e Prosa",
    type: "rapida",
  },
  {
    src: "audio/blueadv/Essa musica.mp3",
    name: "Essa musica",
    band: "Forró Massapê",
    type: "lenta",
  },
  {
    src: "audio/blueadv/Botando o Pé na Estrada.mp3",
    name: "Botando o Pé na Estrada",
    band: "Verso e Prosa",
    type: "rapida",
  },
];